#cloud-config
#
# Copyright (c) 2023 Matt Smith
# MIT License
#
# Cloud ........... : Hetzner Cloud (though this may work with your cloud without any changes)
# Instance Type ... : Shared vCPU, CPX11 (2 vCPU, 2GB RAM)
# OS .............. : Debian 11
#
# Description ..... :
# This builds the latest VyOS 1.3.x (equuleus) ISO and boots it.
# The process takes approx. 25 minutes on the CPX11 instance type.
#
runcmd:
  - apt-get update >/dev/tty1 2>&1
  - apt-get install -y ufw curl >/dev/tty1 2>&1
  - ufw enable >/dev/tty1 2>&1
  - curl -Ls https://raw.githubusercontent.com/mattx86/vyos-iso-cloud-config/main/vyos-iso-cloud-config.sh -o /root/vyos-iso-cloud-config.sh
  - chmod 700 /root/vyos-iso-cloud-config.sh
  - /root/vyos-iso-cloud-config.sh equuleus boot >/dev/tty1 2>&1